CREATE TABLE NOTICES
(
	SEQ int PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(200),
	WRITER VARCHAR(50),
	CONTENT VARCHAR(4000),
	REGDATE DATETIME DEFAULT now(),
	HIT int,
	FILESRC VARCHAR(500)
);

CREATE TABLE MEMBER
(
    UID VARCHAR(50),
    PWD VARCHAR(50),
    NAME VARCHAR(50),
    GENDER VARCHAR(10),
    BIRTH VARCHAR(10),
    IS_LUNAR VARCHAR(10),
    CPHONE VARCHAR(15),
    EMAIL VARCHAR(200),
    HABIT VARCHAR(200),
    REGDATE DATETIME DEFAULT now(),
);



